export const week = {
    pl: ['pon', 'wto', 'śro', 'czw', 'pią', 'sob', 'nie'],
    ua: ['пнд', 'втр', 'срд', 'чтв', 'птн', 'сбт', 'ндл'],
    en: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
}

export const monthNames = {
    pl: [
        'Styczeń',
        'Luty',
        'Marzec',
        'Kwiecień',
        'Maj',
        'Czerwiec',
        'Lipiec',
        'Sierpień',
        'Wrzesień',
        'Październik',
        'Listopad',
        'Grudzień',
    ],
    ua: [
        'Січень',
        'Лютий',
        'Березень',
        'Квітень',
        'Травень',
        'Червень',
        'Липень',
        'Серпень',
        'Вересень',
        'Жовтень',
        'Листопад',
        'Грудень',
    ],
    en: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ],
}
